version: "3.7"
services:
  pg:
    build: ./postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_DB: sgtd
      POSTGRES_USER: sgtd
      POSTGRES_PASSWORD: sgtd
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
